# Generated by Django 5.0.4 on 2024-05-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_test_dt_test_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
